version: 0.2
phases:
  pre_build:
    commands:
      - GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF:-$CODEBUILD_SOURCE_VERSION}
      - export GIT_BRANCH=$(echo $GIT_BRANCH | sed "s|branch/||" | sed "s|/|-|g" | sed "s|refs-heads-||")
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - echo $GIT_BRANCH 
      - sam build --template template.yaml
  post_build:
    commands:
      - sam deploy -template template.yaml