version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    # jq is also installed
    # commands:
    #   - apt install -y jq
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy