version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    # jq is also installed
    # commands:
    #   - apt install -y jq
  build:
    commands:
      - echo "${CODEBUILD_WEBHOOK_HEAD_REF}"
      - sam build
  post_build:
    commands:
      - bash ./pipeline_scripts/get_last_snapshot.sh
      - sam deploy --parameter-overrides DBSnapshotIdentifier=$ARN Env="${CODEBUILD_WEBHOOK_HEAD_REF}"